spring:
  application:
    name: mementauto
  datasource:
#    url: jdbc:postgresql://26.215.168.106:5432/mementauto
    url: jdbc:postgresql://localhost:5432/mementauto
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  file:
    name: mementauto.log
server:
  port: 8080
